In [10]:
import sys; sys.path.append("..")

import pandas as pd
from sklearn.model_selection import train_test_split

from models.models import (
    train_classification_models,
    evaluate_classification,
)

from models.models import save_model_local

In [11]:
import joblib

(
    X_train, X_test,
    X_train_sc, X_test_sc,
    y_train_c, y_test_c,
    feature_names
) = joblib.load("../data/processed/splits.pkl")

In [12]:
models = train_classification_models(X_train_sc, y_train_c)

results = evaluate_classification(models, X_test_sc, y_test_c)
results

               Modelo  Accuracy  Precision  Recall      F1
1        DecisionTree    0.7149     0.3936  0.4088  0.4010
2        RandomForest    0.8009     0.8416  0.1814  0.2985
0  LogisticRegression    0.7675     0.6667  0.0085  0.0169

In [13]:
from models.models import save_model_local

save_model_local(models["RandomForest"], "rf_model")
save_model_local(models["LogisticRegression"], "lr_model")

'models/lr_model.pkl'

In [14]:
results[results["Modelo"].isin(["DecisionTree", "RandomForest"])]

         Modelo  Accuracy  Precision  Recall      F1
1  DecisionTree    0.7149     0.3936  0.4088  0.4010
2  RandomForest    0.8009     0.8416  0.1814  0.2985

In [15]:
import pandas as pd
import yaml

with open("../config/config.yaml") as f:
    config = yaml.safe_load(f)

df_feat = pd.read_csv("../" + config["data"]["processed_path"])

In [16]:
from pycaret.classification import *

df_model = df_feat.copy()
df_model = df_model.drop(columns=[
    "Artist", "Track",
    "Stream", "Views", "Likes", "Comments"
], errors="ignore")
df_model = df_model.dropna()

clf = setup(
    data=df_model,
    target="viral",
    session_id=42
)

compare_models()

AdaBoostClassifier(algorithm='SAMME.R', estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=42)

In [17]:

light_model = create_model('lightgbm')

# (recomendado)
light_model = tune_model(light_model)

# (opcional pero PRO)
final_model = finalize_model(light_model)

# ✅ GUARDAR LIGHTGBM
save_model(final_model, "best_pycaret_model")

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Album_type', 'Danceability',
                                              'Energy', 'Key', 'Loudness',
                                              'Speechiness', 'Acousticness',
                                              'Instrumentalness', 'Liveness',
                                              'Valence', 'Tempo', 'Duration_ms',
                                              'Licensed', 'official_video',
                                              'engagement_rate', 'log_Views',
                                              'log_Likes', 'log_Comments',
                                              'log_Stream',...
                  LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, importance_type='split',
                                 learning_rate=0.1, max_depth=-1,
                                 min_child_samples=20, min_child_weight=0.001,
                                 min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                 num_leaves=31, objective=None, random_state=42,
                                 reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
                                 subsample_for_bin=200000, subsample_freq=0))],
          verbose=False),
 'best_pycaret_model.pkl')